---
# tasks file for nginx

- name: Installation de nginx
  yum:
   name: nginx
   state: present

- name: Arret et desactivation du server apache
  systemd:
   name: httpd
   state: stopped
   enabled: no

- name: creation rep /var/www/{{ item }}/html
  file:
   path: /var/www/{{ item }}/html
   state: directory
   mode: '0755'
   owner: root
   group: root
   recurse: yes
  loop:
    "{{ sites }}"

- name: creation des fichiers index.html a partir de modele
  template:
   src: index.j2
   dest: /var/www/{{ item }}/html/index.html
  loop:
    "{{ sites }}"

- name: creation des repertoires pour les sites web
  file:
   path: /etc/nginx/sites-{{ item }}
   state: directory
  loop:
    - available
    - enbaled

- name: Modification nginx.conf
  lineinfile:
   path: /etc/nginx/nginx.conf
   regexp: '^# Settings'
   insertbefore: '^# Settings'
   line: '   include /etc/nginx/sites-enabled/*.conf;'

- name: creation du serveur block file
  template:
   src: site.j2
   dest: /etc/nginx/sites-available/{{ item }}.conf
  loop:
    "{{ sites }}"
  
  notify:
   - restart nginx
   
     # - name: activation des sites
     #   file:
     #    src: /etc/nginx/sites-available/{{ item }}.conf
     #    dest: /etc/nginx/sites-enabled/{{ item }}.conf
     #    state: link
     #    loop:
     #     ipssi.dev
     #   ipssi.form
     
